#https://zellwk.com/blog/github-actions-deploy/

name: Deploy to Digital Ocean

concurrency: production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: nuzhdiki
      url: https://nuzhdiki.timagribanov.com
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: checkout repo
        uses: actions/checkout@v3.5.3
      - name: show repo contents
        run: ls -al
      - name: deploy
        run: rsync -ar --exclude=".github" --exclude=".git" --exclude=".vscode" --exclude=".gitignore" . ${{ secrets.USER }}@${{ secrets.IP }}:${{ secrets.PATH }}
