name: Deploy to Digital Ocean

concurrency: production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: nuzhdiki
      url: https://nuzhdiki.timagribanov.com
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      # - name: Adding Known Hosts
      #   run: ssh-keyscan -H ${{ secrets.IP }} >> ~/.ssh/known_hosts
      - name: deploy
        run: rsync -ar --exclude=".github" --exclude=".git" --exclude=".vscode" --exclude=".gitignore" . ${{ secrets.USER }}@${{ secrets.IP }}:${{ secrets.PATH }}
