name: Deploy to Digital Ocean

concurrency: production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: nuzhdiki
      url: https://nuzhdiki.timagribanov.com
    steps:
      - name: install ssh keys
        run: |
            install -m 600 -D /dev/null ~/.ssh/id_rsa
            echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.IP }} > ~/.ssh/known_hosts
      - name: connect and pull
        run: ssh ${{ secrets.USER }}@${{ secrets.IP }} "cd ${{ secrets.PATH }} && git checkout main && git pull && exit"
      - name: cleanup
        run: rm -rf ~/.ssh
